### ISSUE TITLE
Create a page describing the implementation of the project

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/adopt-a-drain#129]
Spawned from #106 

From @jeanwalshie:
> a related idea: someone suggested that we include information about how this was developed and how people can do something similar in their own city. the logos go to our agency pages, where one could potentially piece it all together, but there's nothing about this particular app and how it came to be. thoughts?

**Comment by jszwedko** [comment]
Code for America has some info related to this via https://www.codeforamerica.org/products/adopt-a-hydrant/ and https://github.com/codeforamerica/adopt-a-hydrant, but could probably use more info about redeploying it. We could either help them update it and point people there, or host this information ourselves (probably in the [README](https://github.com/sfbrigade/adopt-a-drain/blob/production/README.md) of this project?).

**Comment by howdoicomputer** [comment]
Ah, reminds me of https://github.com/sfbrigade/adopt-a-drain/issues/109

Which I've still not gotten to! Man, this application really screams for multi-tenancy where we just have a pre-processor per data source/noun. Anyway, I can probably cover this when I address #109 - it'll take me several hours  to go through the entire code base and get it written up to the point where I'd be satisfied.

However, just describing how to deploy this with a custom noun shouldn't take too long; all you're really doing is defining a rake task that pulls down data, formats it, then stuffs it into the database. I can see most data sets remaining static too since we're describing infrastructure. Dynamic nouns

**Comment by jeanwalshie** [comment]
haha, you lost me, @howdoicomputer! my idea was to have some simple language for the average joe about how the app was developed in partnership with the Code for SF brigade and the City of SF, using open data and open source something or other. i can work with @jasonlally on this.

**Comment by jeanwalshie** [comment]
@howdoicomputer -- i'd like to close this cuz in my mind it's done. maybe you can create a new issue if needed?
