### ISSUE TITLE
Require separate entry of first and last name upon sign up (to facilitate data entry)

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#159]
in order to upload contact information of adopters into our email program the first and last name need to be separated. i can do this manually but i thought it might be good to set it up that way when users sign up. thoughts?

**Comment by jszwedko** [comment]
Seems reasonable to me -- we'd have to deal with splitting existing users' names.

**Comment by jeanwalshie** [comment]
great, i'm hoping we can implement this! and by "we" i mean you guys :)

**Comment by jszwedko** [comment]
Submitted #167 which will:

* Update the forms to have separate inputs for first and last name.
* Split existing users names into first and last on the first space (everything up to the first space will be the first name, the remainder will be the last name)
* I didn't make last name required because many of the existing users just put the first name in the existing field, please let me know if you'd like me to make it required and, if so, what value to use for existing users' names

**Comment by jeanwalshie** [comment]
Thanks, Jesse! I agree last name should not be required.

**Comment by jszwedko** [comment]
Pushed up these changes, let me know what you think!

**Comment by jeanwalshie** [comment]
looks great, thank you!! i'm gonna close this. yippee!
