### ISSUE TITLE
possible bug in German?

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#202]
i got this feedback from a user: 

"If you check out the German internationalization, the names of the drains come up as {thing_name}"

i don't know exactly what this means or how to check it, but maybe someone can take a look?

**Comment by jszwedko** [comment]
This should be fixed by https://github.com/sfbrigade/adopt-a-drain/commit/78639d9499e838774f0fe76333dc92b761862e76.

It means that German users would have seen `{thing_name}` rather than the adopted name of the drain in the drain details. Unfortunately, I'm sure there are some other missing pieces to make sure the app is fully internationalized -- I might recommend just restricting to English unless have anyone that can manage the translations and other internationalization concerns.

**Comment by jeanwalshie** [comment]
thanks, @jszwedko. how do we restrict to English? works for me!

**Comment by jszwedko** [comment]
We can do that in the code -- I'll make that adjustment now.

**Comment by jszwedko** [comment]
Should be done by 5a32412
