### ISSUE TITLE
Change Adopt a Drain logo hyperlink to open in a new tab.

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#203]
Currently when you click on the Adopt a Drain logo it opens the AAD page, which is not helpful. Change the logo hyperlink to open in a new tab the link below. 
http://sfwater.org/index.aspx?page=905

**Comment by jszwedko** [comment]
Hi @FrankieBurton, I'm happy to make this change if we _really_ want it, but the general recommendation for web applications is that clicking the logo of a page takes you to the home page of the application (see Twitter and Facebook for examples or https://www.nngroup.com/articles/113-design-guidelines-homepage-usability/ for more details). Since this is a single page application, I would also be open to just removing the hyperlink altogether until we have multiple pages, but I believe linking to a completely different domain would be disorienting for users.

Let me know what you think!

**Comment by FrankieBurton** [comment]
Thanks for the explanation @jszwedko. I am ok leaving it as is then unless @jeanwalshie has a different preference.

**Comment by jeanwalshie** [comment]
hi all, fine leaving it as is! thank you!
