### ISSUE TITLE
Decrease size of logos and fix scaling issues

### ISSUE THREAD

**Issue by FrankieBurton** [sfbrigade/adopt-a-drain#208]
Decrease the size of the SFPUC, Public Works, DataSF, Code for San Francisco and Code for America logo thumbnails on the home page to make them all visible without scrolling. (Currently you cannot see the Code for America logo.)

**Comment by jszwedko** [comment]
Hi @FrankieBurton, whether or not the logos will be visible without scrolling will depend on how tall your viewport is (i.e. how many pixels tall your web browser window is).

I think are options are:

0. Make them small enough that for _most_ view port sizes you will see them when not logged in (opening either the login form or logging in and seeing your list of drains will likely push the logos "below the fold" after this)
0. Constrain the height of other parts of the side bar (forcing the user to scroll within the side bar). See below gif for an example of what I mean.

![Image of adoptadrain](http://i.imgur.com/Js0ATCo.gif)

Let me know what you think!

**Comment by FrankieBurton** [comment]
I realize that it depends on the view port, but I did not know that term. Thanks - that is a good word to know! :) 

I apologize for not being more clear. I meant to request that the logos be made small enough for most view ports. However, now that I know about the second option I kind of like it. I'd say the logos could be a bit smaller, but it would be nice to be able to see them at all times. It further reinforces the partnership aspect of this website that is an important key message for AAD. 

@jeanwalshie Any preference between these two options?

**Comment by jszwedko** [comment]
👍  agreed, we should shrink the logos either way.

I'll do some more research, but it looks like we should be pretty safe with 700px on desktop if we decide to go that route.

**Comment by jszwedko** [comment]
@jeanwalshie what do you think about the above options?

**Comment by FrankieBurton** [comment]
@jszwedko will the fifth logo be visible with option 2? If so I prefer it. @jeanwalshie let us know if you have a strong preference otherwise we will go with option 2.

**Comment by jeanwalshie** [comment]
hi all! i don't have a strong preference. but remember the page looks different after sign in (the video disappears) so there's more space on the left bar.

here's what the logos currently look like for me: 
![image](https://cloud.githubusercontent.com/assets/15933453/21440961/904daf04-c84a-11e6-82b2-4b22169ebc5e.png)
the two city logos don't shrink as well as the other three.

**Comment by FrankieBurton** [comment]
Yeah they look crammed in there. Is there any way to fix this @jszwedko?

**Comment by jszwedko** [comment]
:+1: I'll give option 2 a shot. I'd like to get the changes in #201 out there first just to clear up the backlog since this change may require some more back and forth to get right.

**Comment by jeanwalshie** [comment]
@jszwedko works for me!

**Comment by jszwedko** [comment]
@FrankieBurton @jeanwalshie got around to taking a crack at this one. After playing around with it for a bit, I actually ended up with #225 which makes the logos smaller and removes the CFA logo since it was easier to lay out 4 logos. You can see the end result here: http://adoptadrainsf-staging.herokuapp.com/ (check it out on mobile too).

CFA isn't an active partner of the project, but they were instrumental in the initial Adopt-a-Hydrant project from which this is based. I'm curious if either of you have thoughts about other places we might put their logo (or if you think it should go back in the sidebar).

**Comment by jeanwalshie** [comment]
thank you @jszwedko!

a few things:
1) the logos look pixelated on my large computer screen (on the test site.) not sure why that is. (couldn't seem to attach an image so I'm attaching a file -- sorry)  I'm not a designer but I think if we provide you vector files (.pdf) vs. raster files (jpg.) that might take care of this issue? I can look into this...
2) I'm fine with removing the CFA logo because they haven't been involved in this iteration and we DO mention them in the "background" section. 
3) now that Dep't of Technology will be providing ongoing support (hurray!), we will want to add their logo. but I will make a separate issue for this -- and maybe it can be @SFgov 's first assignment! :) this will increase the number of logos to five again (two lines, likely)
[pixelated logos.docx](https://github.com/sfbrigade/adopt-a-drain/files/755972/pixelated.logos.docx)

**Comment by jszwedko** [comment]
Vector files (SVG preferably) would definitely scale better to smaller viewports. If you could find one for DPW and SF Water, I can track one down for Code for SF. @jasonlally do you know if DataSF has a vector logo floating about?

**Comment by jszwedko** [comment]
When we add the DT logo, we _could_ re-add CFA one and go to 2 lines of 3.

**Comment by jeanwalshie** [comment]
![sfwps-horz-4c](https://cloud.githubusercontent.com/assets/15933453/23573185/08c5bed4-0029-11e7-9b6c-a3567d575bfa.jpg)
![sfwps-horz-t1](https://cloud.githubusercontent.com/assets/15933453/23573186/08ca636c-0029-11e7-947e-7407b8fd6cc8.png)

ok, here are SFPUC and DPW logos in PNG and JPG. will these work? (i tried to upload AI files but they're not accepted...

**Comment by jszwedko** [comment]
👍 I can play with these some more

**Comment by jeanwalshie** [comment]
@jszwedko i get a message that says "don't accept those file types." maybe i can just email them to you?

**Comment by jszwedko** [comment]
Aha, I see, yeah Github does limit the file types. Email is fine!

**Comment by jeanwalshie** [comment]
ok, i emailed them to you!

**Comment by jafowler49** [comment]
Pull request ready for review

https://github.com/sfbrigade/adopt-a-drain/pull/237

**Comment by jeanwalshie** [comment]
this looks good to me!

**Comment by jafowler49** [comment]
Looks like this is done, closing!
