### ISSUE TITLE
Replace text for 2nd email

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#213]
Please update the text of the 2nd email as follows: 

==================================

Wow! You adopted another drain. Thank you. 

Remember, if you encounter medical waste, construction debris, toxic materials or some other problem with your drain, [report it to 311](https://mobile311.sfgov.org/reports/new?service_id=518d5c0d601827e388000156) to have it cleared by the City. 

As always, please let us know if you have any feedback or questions about this program. We love to hear from you! 

Thank you, 
Your friends at the San Francisco Public Utilities Commission 
415-554-3289 
info@sfwater.org 

P.S. You also can Adopt-a-Street. In addition to clearing your drain, you and a neighborhood group can adopt a larger area and take responsibility for helping to keep the street and sidewalk there clean. Learn more about this Public Works program [here](http://www.sfpublicworks.org/get_involved/adopt-street-program). 

_The City and County of San Francisco won't be held responsible for anything that happens to you or others in service of maintaining your drain. Please be careful!_

**Comment by jszwedko** [comment]
:+1: 

Adjusted to match this in c71a9f0

I did adjust the hyperlink in the penultimate paragraph to include the whole of "Learn more about this Public Works program here." as the link text. This is more in-line with web accessibility recommendations (http://webaim.org/techniques/hypertext/) because "here" is ambiguous without additional context. Please let me know if you'd like different link text though.
