### ISSUE TITLE
Add text to "What does it mean to adopt a drain" button

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#247]
I would like to add this content to the bottom of the pop up: 

Volunteer Developer Opportunities

Are you a programmer with Ruby on Rails experience who wants to help improve and maintain the Adopt a Drain application? Don't be shy! We're always seeking assistance with the code! Get involved and follow our GitHub page. (LINK TO PAGE)

**Comment by jeanwalshie** [comment]
sweet! thanks @jszwedko. what's next to make this live? @jafowler49

**Comment by jszwedko** [comment]
Hi @jeanwalshie,

Since this is just a copy update, I think either you or another SFPUC representative reviewing would be sufficient. You can see the changes via this temporary app: https://adoptadrainsf-staging-pr-249.herokuapp.com/

Please see https://github.com/sfbrigade/adopt-a-drain/pull/249#issuecomment-315477185 for more details about the new change review process (also sent as an e-mail).

**Comment by jeanwalshie** [comment]
thanks @jszwedko! this looks great. the one thing i would change is to move the Contact Us info to the very bottom so it's not buried in there. Thanks so much!

**Comment by jszwedko** [comment]
@jeanwalshie pushed another commit moving the Contact Us to the bottom. Do you mind taking another look (https://adoptadrainsf-staging-pr-249.herokuapp.com/) and I'll merge this in?

Thank you!

**Comment by jeanwalshie** [comment]
@jszwedko looks great, let's roll!

**Comment by jszwedko** [comment]
Awesome, rolling this out now!
