### ISSUE TITLE
Remove Program Background button and associated pop up

### ISSUE THREAD

**Issue by jeanwalshie** [sfbrigade/adopt-a-drain#248]
I would like to remove this button because I feel it's a bit redundant, we are creating a page on the SFPUC website that will contain this information, and I feel it's not relevant to the majority of folks visiting the site. 

The language about helping with the code will be retained in the "What it Means to Adopt a Drain" tab (in another issue.)

thanks!

**Comment by jeanwalshie** [comment]
thanks @jszwedko! what's the next step on this? does @jafowler49 need to review?

**Comment by jszwedko** [comment]
Hi @jeanwalshie,

Since this is just a copy update, I think either you or another SFPUC representative reviewing would be sufficient. You can see the changes via this temporary app: https://adoptadrainsf-staging-pr-249.herokuapp.com/

Please see https://github.com/sfbrigade/adopt-a-drain/pull/249#issuecomment-315477185 for more details about the new change review process (also sent as an e-mail).

**Comment by jeanwalshie** [comment]
hey @jszwedko, 

this works for me on chrome, but when i tried on explorer i get an error message where the video should be. the video doesn't play and it says to download javascript. i guess that's just something on my end, right?

**Comment by jszwedko** [comment]
Interesting, I can't imagine any of these changes would have affected that. Do you see the same issue in production with IE?

Closing this out since I rolled out #249, but let me know and I can look into this more if you see it in production too.
