### ISSUE TITLE
Accept feedback from users

### ISSUE THREAD

**Issue by kmcurry** [sfbrigade/adopt-a-drain#251]
As a User, I want to provide feedback or contact you.

Adopt-a-drain in St. Paul and Oakland both have links to provide feedback. Both use mailto: hyperlinks to open email, which gets the job done. A better approach might be a city UserVoice or similar service.

**Comment by jszwedko** [comment]
Hi @kmcurry,

This does actually exist in one of the modals (the button that says "What Does it Mean To Adopt a Drain?"); however, I can see that a user would probably not think to look there for the feedback link. @jeanwalshie what do you think about putting it at the bottom of the sidebar?

**Comment by jeanwalshie** [comment]
hi @kmcurry,

yes, definitely agree that a contact link should be provided. i'm not opposed to putting it at the bottom of the sidebar, but i do want to avoid getting questions that could have been answered if the user had read the other info on the page. so for now i think it's best to keep the email address on the "What Does It Mean to Adopt a Drain" modal. 

And of course, now I'm thinking it would be good to remove that "Click here to learn more" sentence, because it's obvious and none of the other buttons have that text, AND make the button have rounded corners like the other ones... but that's a separate issue, which i'll create now :)

**Comment by jszwedko** [comment]
:+1: I'm fine with keeping it there for now.
