### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by afomi** [sfbrigade/adopt-a-drain#67]
spent an hour trying to get an ENV up on Windows 9, without luck

**Comment by jszwedko** [comment]
I assume you mean Windows 10 :smile: -- unless I'm missing something. We _could_ solve this by keeping an up-to-date Vagrant image, I feel like I'd rather that than maintaining instructions for installing Ruby and Postgres on Windows.

**Comment by afomi** [comment]
haha - yep. 10 - and ya, Vagrant is a good idea.  I'll also keep an eye out for good Windows instructions on getting Ruby and Postgres going (if there are any)

**Comment by howdoicomputer** [comment]
I am working off of a Windows 10 machine and recently submitted a PR that added the `tzinfo` gem for Windows support.

I'm writing code and everything is working properly.

**Comment by jszwedko** [comment]
@howdoicomputer good to hear :) I think some of the confusion for this issue was around running Postgres and Ruby on Windows, but I may be misremembering. We could add some links to other documents for how to do that though.

**Comment by howdoicomputer** [comment]
Windows development is always tricky for languages that require C extensions. I'll write a guide somewhere but potential Windows developers would need to install Ruby 2.X, install Ruby DevKit, install Postgres, and then follow the documentation for DevKit so that gems like `json` can have their C extensions compiled correctly.

I also found that there [is a bug](https://github.com/codahale/bcrypt-ruby/issues/116) in the `bcrypt` gem that required some custom installation steps as well.

I mean, it's a bit tricky but if the steps are laid out it takes less than ten minutes to get everything running to the point that `bundle exec rake test` returns 0 errors.

**Comment by howdoicomputer** [comment]
Alright, I went ahead and wrote a lengthy guide in the wiki for setting this up on Windows.

https://github.com/sfbrigade/adopt-a-drain/wiki/Windows-Development-Environment

Is this issue ready for closing?

**Comment by jszwedko** [comment]
Indeed it is, these instructions are great!
